### ISSUE TITLE
Add prefix P0, P1 or P2 to files

### ISSUE THREAD

**Issue by odile9999** [odile9999/PIL#7]
P0 : for old PIRENEA setup
P1 : for new PIRENEA setup
P2 : for PILAB (PIRENEA-2) setup

**Comment by odile9999** [comment]
Rajouter une section SETUP dans le fichier PIL.ini, avec comme unique paramètre:
setup=PIRENEA ou
setup=PILAB
La relecture du paramètre setup AU DEMARRAGE devra mettre à jour le cluster EXPERIMENT.

**Comment by odile9999** [comment]
Plutôt faire la relecture du fichier PIL.ini avant de quitter GUI_SetupExperiment.
Modifier aussi Data_Get_Spectrum_Number et ICR_Setup_Sequence pour mettre à jour le préfixe du spectre.
Supprimer DIGIT_5122-Write_Data

**Comment by OdileCoeur-Joly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Nommer les spectres PIRENEA en P0_xx (old pirenea), P1_xx (pirenea), P2_xx (pirenea-2)](https://trello.com/c/jwNvInbz/149-nommer-les-spectres-pirenea-en-p0xx-old-pirenea-p1xx-pirenea-p2xx-pirenea-2)
